services:
  # Standard node container
  claude-code:
    image: claude-code:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Main repository mount
      - ..:/home/coder/project:rw
      # Claude Code submodule mount (read-only)
      - ../claude-code-docker:/home/coder/claude-code-docker:ro
      # Config mounts at multiple possible locations
      - ./config:/opt/context/config:ro
      - ./config:/home/coder/project/config:ro
      - ./config:/home/coder/config:ro
      # Documentation files
      - ./CLAUDE.md:/home/coder/project/CLAUDE.md:ro
      - ./MAX-PLAN.md:/home/coder/project/MAX-PLAN.md:ro
      - ./MAX-PLAN.md:/home/coder/docs/MAX-PLAN.md:ro
      # Startup script
      - ./startup.sh:/usr/local/bin/startup.sh:ro
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_USE_MAX_PLAN=${CLAUDE_USE_MAX_PLAN}
    # Keep container running
    tty: true
    stdin_open: true
    # Override the default command to initialize paths and keep container alive
    entrypoint: ["/bin/bash", "-c", "chmod +x /usr/local/bin/startup.sh && /usr/local/bin/startup.sh tail -f /dev/null"]