services:
  # Standard node container
  claude-code:
    image: claude-code:latest
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      - ..:/home/coder/project:rw
      - ../claude-code-docker:/home/coder/claude-code-docker:ro
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    # Keep container running
    tty: true
    stdin_open: true
    # Override the default command to keep container alive
    command: tail -f /dev/null