services:
  claude-code:
    image: claude-code:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Main repository mount
      - ..:/home/coder/project:rw
      # FCM resources (models, config, validation)
      - ./models:/home/coder/project/models:ro
      - ./config:/home/coder/project/config:rw
      - ./validation:/home/coder/project/validation:ro
      # Documentation
      - ./CLAUDE.md:/home/coder/project/CLAUDE.md:ro
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    tty: true
    stdin_open: true
    command: tail -f /dev/null