services:
  # Standard node container
  claude-code:
    image: claude-code:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Main repository mount
      - ..:/home/coder/project:rw
      # Claude Code submodule mount (read-only)
      - ../claude-code-docker:/home/coder/claude-code-docker:ro
      # Config mounts at multiple possible locations
      - ./config:/opt/context/config:ro
      - ./config:/home/coder/project/config:ro
      - ./config:/home/coder/config:ro
      # CLAUDE.md at project root
      - ./CLAUDE.md:/home/coder/project/CLAUDE.md:ro
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    # Keep container running
    tty: true
    stdin_open: true
    # Override the default command to keep container alive
    command: tail -f /dev/null