name: Build Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build_image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Checkout utils repo
        uses: actions/checkout@v4
        with:
          repository: deepworks-net/utilities.docker
          ref: develop
          path: scripts/utils
        
      # Make scripts executable before the build
      - name: Set permissions
        run: |
          chmod +x webdna.sh
          chmod +x scripts/build.sh
          chmod +x scripts/utils/funcs.sh

      - name: Parse tag and set environment
        id: env
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          SERVICE_NAME=$(echo $TAG | rev | cut -d'-' -f2- | rev)
          DISTRO_FULL=$(echo $TAG | cut -d'-' -f1)
          ENV_FILE="$GITHUB_WORKSPACE/${DISTRO_FULL%[0-9]*}/${DISTRO_FULL}.env"
          IMAGE_NAME="deepworks/webdna"
          
          echo "DOCKER_UTILS_ENV=$ENV_FILE" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_VERSION=$TAG" >> $GITHUB_OUTPUT
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT

      - name: Load environment variables
        shell: bash
        run: |
          while IFS='=' read -r key value; do
            [[ $key =~ ^#.*$ ]] && continue
            [[ -z $key ]] && continue
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
            echo "$key=$value" >> $GITHUB_ENV
          done < "${{ steps.env.outputs.DOCKER_UTILS_ENV }}"
        
      - name: Build Docker image
        run: |
          scripts/build.sh
        shell: bash
        env:
          DOCKER_UTILS_ENV: ${{ steps.env.outputs.DOCKER_UTILS_ENV }}