name: Docker Claude Code Release

on:
  push:
    tags: ['prep']  # Trigger on prep tag

jobs:
  prepare-release:
    uses: deepworks-net/github.actions/.github/workflows/prepare-release.yml@v1
    with:
      changelog_path: CHANGELOG.md
      
  calculate-version:
    uses: deepworks-net/github.actions/.github/workflows/core.action.version_calculator.yml@v1
    outputs:
      next_version: ${{ jobs.calculate-version.outputs.next_version }}
      
  update-files:
    needs: calculate-version
    uses: deepworks-net/github.actions/.github/workflows/core.action.version_updater.yml@v1
    with:
      version: ${{ needs.calculate-version.outputs.next_version }}
      files: |
        config/claude.config.fcm.json
        CLAUDE.md
        README.md
        config/evolution.log.json

  docker-build:
    needs: update-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            deepworks/claude-code:latest
            deepworks/claude-code:${{ needs.calculate-version.outputs.next_version }}
          platforms: linux/amd64,linux/arm64

  create-release:
    needs: [calculate-version, docker-build]
    uses: deepworks-net/github.actions/.github/workflows/release-drafter.yml@v1
    with:
      tag: ${{ needs.calculate-version.outputs.next_version }}
      name: "Docker Claude Code v${{ needs.calculate-version.outputs.next_version }}"
      draft: false
      prerelease: false